server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8061/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/patient/**
          filters:
            - RewritePath=/patient/(?<path>.*), /$\{path}
        - id: ui-service
          uri: lb://ui-service
          predicates:
            - Path=/ui/**
          filters:
            - RewritePath=/ui/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: patient
        url: /v3/api-docs/patient
      - name: ui
        url: /v3/api-docs/ui

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans