version: "3"
services:

  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mediscreen
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - mysql_db:/var/lib/mysql:rw


  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mediscreen09
    ports:
      - 27017:27017

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    ports:
      - "9411:9411"

  discovery-service:
    container_name: discovery-service
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    image: discovery-service:latest
    environment:
      ZIPKIN_HOST: zipkin
    ports:
      - 8061:8061
    restart: always

  note-service:
    container_name: note-service
    build:
      context: ./note-service
      dockerfile: Dockerfile
    image: note-service:latest
    ports:
      - 9100:9100
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8061/eureka/
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SPRING_DATA_MONGODB_URI: mongodb://root:example@mongo:27017/admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      network: default
      ZIPKIN_HOST: zipkin
    depends_on:
    - mongo


  patient-service:
    container_name: patient-service
    build:
      context: ./patient-service
      dockerfile: Dockerfile
    image: patient-service:latest
    ports:
      - 9000:9000
    environment:
      spring.datasource.url: jdbc:mysql://mysqldb:3306/mediscreen
      spring.datasource.username: root
      spring.datasource.password: password
      spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
      spring.jpa.show-sql: true
      spring.jpa.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      spring.jpa.hibernate.ddl-auto: create
      spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8061/eureka/
      ZIPKIN_HOST: zipkin
    depends_on:
      - mysqldb


  assessment-service:
    container_name: assessment-service
    build:
      context: ./assessment-service
      dockerfile: Dockerfile
    image: assessment-service:latest
    ports:
      - 9200:9200
    environment:
     eureka.client.serviceUrl.defaultZone: http://discovery-service:8061/eureka/
     ZIPKIN_HOST: zipkin
    depends_on:
      - discovery-service

  client-ui:
    container_name: client-ui
    build:
      context: ./client-ui
      dockerfile: Dockerfile
    image: client-ui:latest
    ports:
      - 8080:8080
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8061/eureka/
      ZIPKIN_HOST: zipkin
    depends_on:
      - discovery-service



volumes:
  mysql_db:
  mongo_db:
