spring:
  application:
    name: report-service

server:
  port: 9200

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

#  config:
#    import: "optional:configserver:http://localhost:8088"
