spring:
  application:
    name: assessment-service

server:
  port: 9200

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

#  config:
#    import: "optional:configserver:http://localhost:8088"

management:
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:localhost}:9411/api/v2/spans
