#spring:
#  config:
#    import: "optional:configserver:http://config-service:8088"
#    activate:
#      on-profile: docker
#---

server:
  port: 8080

spring:
  application:
    name: ui-service
  cloud:
    config:
      import-check:
        enabled: false
#
#  config:
#    import: "optional:configserver:http://localhost:8088"
  main:
    allow-circular-references: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
