spring:
  config:
    import: "optional:configserver:http://config-service:8088"
    activate:
      on-profile: docker
---
spring:
  application:
    name: ui-service
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:mysql://localhost:3306/mediscreen
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: false
  config:
    import: "optional:configserver:http://localhost:8088"
  main:
    allow-circular-references: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
