server:
  port: 8061

spring:
  application:
    name: discovery-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/



management:
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:localhost}:9411/api/v2/spans
