spring:
  application:
    name: discovery-service

server:
  port: 8061

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

#  config:
#    import: "optional:configserver:http://localhost:8088"