server:
  port: 8080
  error:
    path: /error
    whitelabel:
      enabled: false

spring:
  application:
    name: client-ui
  cloud:
    openfeign:
      client:
        config:
          assessment-service:
            url: http://localhost:9200
          note-service:
            url: http://localhost:9100
          patient-service:
            url: http://localhost:9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/


management:
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:localhost}:9411/api/v2/spans


mediscreen:
  proxy:
    - patient: localhost
    - note: