spring:
  application:
    name: client-ui

server:
  port: 8080
  error:
    path: /error
    whitelabel:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/


management:
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:localhost}:9411/api/v2/spans
