server:
  port: 9100

spring:
  application:
    name: note-service
  jpa:
    hibernate:
      ddl-auto: create

  data:
    mongodb:
      authentication-database: ""
      username: ""
      database: "mediscreen09"
      password: ""
      port: 27017
      uri: mongodb://localhost:27017/mediscreen09
      host: ${MONGO_HOST:localhost}
      security:
        authorization: enabled

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/


management:
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:localhost}:9411/api/v2/spans
