server:
   port: 9000

spring:
  application:
    name: patient-service
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:mysql://localhost:3306/mediscreen
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true
  cloud:
    config:
      import-check:
        enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

management:
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:localhost}:9411/api/v2/spans
